name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: write/packages/write-module

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: write/packages/write-module/package.json

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

    - name: Build
      run: npm run build
